### ISSUE TITLE
Is the lib package missing?

### ISSUE THREAD

**Issue by Truoji** [zealscott/SynMeter#1]
I wanted to reproduce your code, but I found that I was missing the lib package.
How can I get it? **Thanks!**
[https://github.com/zealscott/SynMeter/blob/3758663ecd029b250c7e9d64ff8108865157d891/scripts/tune_evaluator.py#L11](url)

`from lib.info import *`
![b3f34c29c32d72d1d39513be82bcb46](https://github.com/zealscott/SynMeter/assets/82994187/95206288-b68b-4d44-8599-9c4666ce4e61)

**Comment by yuntaod** [comment]
Hi @Truoji ,

Thanks for your remind. The lib dictionary is missing due to the keywords matching in`.gitignore`.  I have fixed it and uploaded the `lib` dictionary. Let me know if any more problems.
