### ISSUE TITLE
Adding a new dataset - how to create dataset_name.json

### ISSUE THREAD

**Issue by kirilzilla** [zealscott/SynMeter#2]
Hi, and thank you for this excellent library!

I’m interested in evaluating the provided models using proprietary datasets. However, I couldn’t find any guidance in the paper or the repository on how to automatically generate the required JSON files in the format:

`datasets/{dataset_name}/{dataset_name}.json`

Could you provide instructions or tools for generating these JSON files?

Thank you!

**Comment by yuntaod** [comment]
Hi @kirilzilla,

Thank you for your interest in this project! The JSON file is generated by calculating the statistics of each column, which you can easily accomplish using `pandas`. Additionally, the type of each column and the dataset's task are manually defined. You can also customize the size of the training, validation, and test sets based on your dataset's requirements.
